import type { Metadata } from "next";
import { Roboto_Mono, Nunito } from "next/font/google";
import "./globals.css";
import Sidebar from "./Components/Sidebar/Sidebar";
import GlobalStyleProvider from "./providers/GlobalStyleProvider";
import ContextProvider from "./providers/ContextProvider";
import { ClerkProvider } from "@clerk/nextjs";
import { auth } from "@clerk/nextjs/server";
import '@radix-ui/themes/styles.css';


const nunito = Nunito({ subsets: ["latin"], display: "swap" });
const roboto_mono = Roboto_Mono({ subsets: ["latin"], display: "swap" });


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const {userId} = auth()
  return (
    <ClerkProvider>
    <html lang="en">
      <body className={nunito.className}>
        <ContextProvider>
        <GlobalStyleProvider>
        {userId && <Sidebar />}
        <div className={`w-full ${roboto_mono.className}`}>
        {children}
        </div>
        </GlobalStyleProvider>
        </ContextProvider>
        </body>
    </html>
    </ClerkProvider>
  );
}
